import { z } from "zod";

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SCHOOL_ADMIN: "SCHOOL_ADMIN",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT",
  PARENT: "PARENT",
  STAFF: "STAFF",
  FINANCE_OFFICER: "FINANCE_OFFICER",
  LIBRARIAN: "LIBRARIAN",
  HR_OFFICER: "HR_OFFICER"
} as const;

export const roleSchema = z.enum([
  ROLES.SUPER_ADMIN,
  ROLES.SCHOOL_ADMIN,
  ROLES.TEACHER,
  ROLES.STUDENT,
  ROLES.PARENT,
  ROLES.STAFF,
  ROLES.FINANCE_OFFICER,
  ROLES.LIBRARIAN,
  ROLES.HR_OFFICER
]);

export type Role = z.infer<typeof roleSchema>;

export const PERMISSIONS = {
  PROFILE_READ: "profile.read",
  SCHOOLS_READ: "schools.read",
  SCHOOLS_CREATE: "schools.create",
  SCHOOLS_UPDATE: "schools.update",
  SCHOOLS_DELETE: "schools.delete",
  ADMINS_MANAGE: "administrators.manage",
  SUBSCRIPTIONS_MANAGE: "subscriptions.manage",
  REVENUE_READ: "revenue.read",
  USERS_MANAGE: "users.manage",
  SCHOOL_DASHBOARD_READ: "school.dashboard.read",
  SCHOOL_OPERATIONS_MANAGE: "school.operations.manage",
  ADMISSIONS_MANAGE: "admissions.manage",
  ACADEMIC_MANAGE: "academic.manage",
  ATTENDANCE_MANAGE: "attendance.manage",
  EXAMINATION_MANAGE: "examination.manage",
  LMS_MANAGE: "lms.manage",
  LMS_ACCESS: "lms.access",
  FINANCE_MANAGE: "finance.manage",
  ADVANCED_FINANCE_MANAGE: "advanced-finance.manage",
  HR_MANAGE: "hr.manage",
  LIBRARY_MANAGE: "library.manage",
  COMMUNICATION_MANAGE: "communication.manage",
  REPORTS_MANAGE: "reports.manage",
  DOCUMENTS_MANAGE: "documents.manage",
  CERTIFICATES_MANAGE: "certificates.manage",
  MEETINGS_MANAGE: "meetings.manage",
  CMS_MANAGE: "cms.manage",
  MOBILE_API_MANAGE: "mobile-api.manage",
  SECURITY_MANAGE: "security.manage",
  PRODUCTION_READINESS_MANAGE: "production-readiness.manage",
  TEACHER_DASHBOARD_READ: "teacher.dashboard.read",
  TEACHER_OPERATIONS_MANAGE: "teacher.operations.manage",
  STUDENT_DASHBOARD_READ: "student.dashboard.read",
  STUDENT_PORTAL_ACCESS: "student.portal.access",
  PARENT_DASHBOARD_READ: "parent.dashboard.read",
  PARENT_PORTAL_ACCESS: "parent.portal.access",
  SETTINGS_THEME_READ: "settings.theme.read",
  AUDIT_READ: "audit.read",
  SYSTEM_SETTINGS_MANAGE: "system-settings.manage",
  BACKUPS_MANAGE: "backups.manage",
  EXPORT_DATA: "data.export"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.SCHOOLS_CREATE,
    PERMISSIONS.SCHOOLS_UPDATE,
    PERMISSIONS.SCHOOLS_DELETE,
    PERMISSIONS.ADMINS_MANAGE,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.REVENUE_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_THEME_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SYSTEM_SETTINGS_MANAGE,
    PERMISSIONS.BACKUPS_MANAGE,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.PRODUCTION_READINESS_MANAGE,
    PERMISSIONS.EXPORT_DATA
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.SCHOOL_DASHBOARD_READ,
    PERMISSIONS.SCHOOL_OPERATIONS_MANAGE,
    PERMISSIONS.ADMISSIONS_MANAGE,
    PERMISSIONS.ACADEMIC_MANAGE,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.EXAMINATION_MANAGE,
    PERMISSIONS.LMS_MANAGE,
    PERMISSIONS.LMS_ACCESS,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.ADVANCED_FINANCE_MANAGE,
    PERMISSIONS.HR_MANAGE,
    PERMISSIONS.LIBRARY_MANAGE,
    PERMISSIONS.COMMUNICATION_MANAGE,
    PERMISSIONS.REPORTS_MANAGE,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.CERTIFICATES_MANAGE,
    PERMISSIONS.MEETINGS_MANAGE,
    PERMISSIONS.CMS_MANAGE,
    PERMISSIONS.MOBILE_API_MANAGE,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.PRODUCTION_READINESS_MANAGE,
    PERMISSIONS.SETTINGS_THEME_READ
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.TEACHER_DASHBOARD_READ,
    PERMISSIONS.TEACHER_OPERATIONS_MANAGE,
    PERMISSIONS.EXAMINATION_MANAGE,
    PERMISSIONS.LMS_MANAGE,
    PERMISSIONS.LMS_ACCESS,
    PERMISSIONS.COMMUNICATION_MANAGE,
    PERMISSIONS.MEETINGS_MANAGE,
    PERMISSIONS.SETTINGS_THEME_READ
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.STUDENT_DASHBOARD_READ,
    PERMISSIONS.STUDENT_PORTAL_ACCESS,
    PERMISSIONS.LMS_ACCESS,
    PERMISSIONS.SETTINGS_THEME_READ
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PARENT_DASHBOARD_READ,
    PERMISSIONS.PARENT_PORTAL_ACCESS,
    PERMISSIONS.SETTINGS_THEME_READ
  ],
  [ROLES.STAFF]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.ADMISSIONS_MANAGE, PERMISSIONS.ACADEMIC_MANAGE, PERMISSIONS.ATTENDANCE_MANAGE, PERMISSIONS.EXAMINATION_MANAGE, PERMISSIONS.LMS_MANAGE, PERMISSIONS.LMS_ACCESS, PERMISSIONS.COMMUNICATION_MANAGE, PERMISSIONS.REPORTS_MANAGE, PERMISSIONS.DOCUMENTS_MANAGE, PERMISSIONS.CERTIFICATES_MANAGE, PERMISSIONS.MEETINGS_MANAGE, PERMISSIONS.CMS_MANAGE, PERMISSIONS.MOBILE_API_MANAGE, PERMISSIONS.SETTINGS_THEME_READ],
  [ROLES.FINANCE_OFFICER]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.FINANCE_MANAGE, PERMISSIONS.ADVANCED_FINANCE_MANAGE, PERMISSIONS.REPORTS_MANAGE, PERMISSIONS.SETTINGS_THEME_READ],
  [ROLES.LIBRARIAN]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.LIBRARY_MANAGE, PERMISSIONS.SETTINGS_THEME_READ],
  [ROLES.HR_OFFICER]: [PERMISSIONS.PROFILE_READ, PERMISSIONS.ATTENDANCE_MANAGE, PERMISSIONS.HR_MANAGE, PERMISSIONS.REPORTS_MANAGE, PERMISSIONS.DOCUMENTS_MANAGE, PERMISSIONS.SETTINGS_THEME_READ]
};

export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
